; FILE FUNCTIONS
CREATE   EQU 3Ch
OPEN     EQU 3Dh
CLOSE    EQU 3Eh
READ     EQU 3Fh
WRITE    EQU 40h
POSITION EQU 42h

; OPEN MODES
READ_MODE       EQU 0
WRITE_MODE      EQU 1
READ_WRITE_MODE EQU 2

; CREATE FILES ATTRIBUTES ATTRIBUTES
JUST_FILE EQU 0

; ERROR CODES
FILE_NOT_FOUND EQU 02
PATH_NOT_FOUND EQU 03
TO_MANY_FILES  EQU 04
ACCESS_DENIED  EQU 05
BAD_HANDLE     EQU 06
DIRECTORY_DEL  EQU 16
NO_MORE_FILES  EQU 18
